{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
stringData:
  passwords.conf: |-
    {{- range $value := .Values.auth.users }}
    {{ $value.username }}:$(MQTT_PASSWORD)
    {{- end }}
{{- end }}